name: Docker Tunnel Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-docker-tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and Run Docker Image - Check Version
        run: |
          docker run -it lambdatest/tunnel:latest --version

      - name: Pull and Run Docker Image - Start Tunnel
        run: |
          docker run -it --name lt lambdatest/tunnel:latest --user johndoe --key ${{ secrets.LT_ACCESS_KEY }}
